// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqbH-DfIGhExwwBNcTQNmdULsNrPm5dK4',
    appId: '1:581851063662:web:d2c8ef4cff805fd5c98d7f',
    messagingSenderId: '581851063662',
    projectId: 'weezywizard-2023',
    authDomain: 'weezywizard-2023.firebaseapp.com',
    storageBucket: 'weezywizard-2023.appspot.com',
    measurementId: 'G-K6J83Q96FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ0Rufn9ZEcAzepU_07TWy72JfTODFb-8',
    appId: '1:581851063662:android:598d7d1c78e8cab6c98d7f',
    messagingSenderId: '581851063662',
    projectId: 'weezywizard-2023',
    storageBucket: 'weezywizard-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC58vXYcbIKKqH3P_MysDyGAfUy6gdWkbc',
    appId: '1:581851063662:ios:904799ef6cbf15bec98d7f',
    messagingSenderId: '581851063662',
    projectId: 'weezywizard-2023',
    storageBucket: 'weezywizard-2023.appspot.com',
    iosClientId: '581851063662-m4lssn3sbtn0h324bnoirf7hl15s9oqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.weezyWizard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC58vXYcbIKKqH3P_MysDyGAfUy6gdWkbc',
    appId: '1:581851063662:ios:18cfadf3e996668cc98d7f',
    messagingSenderId: '581851063662',
    projectId: 'weezywizard-2023',
    storageBucket: 'weezywizard-2023.appspot.com',
    iosClientId: '581851063662-mo16mvq8o16hdpul2pb1g5ec76bgr998.apps.googleusercontent.com',
    iosBundleId: 'com.example.weezyWizard.RunnerTests',
  );
}
